### ISSUE TITLE
Tabs to spaces doesn't work

### ISSUE THREAD

**Issue by DennisKehrig** [davidderaedt/tabtospace-extension#1]
The first line (previously unindented) is indented with four spaces, the other lines stay indented with tabs.
One part of the problems is the \t*, matching even unindentent lines, the other is the limitation to the beginning of a string (^) while not using the m modifier, which would make it match the beginning of every line.

I think if you want to only replace the beginning of lines, you need to call a function as the second argument to replace. This function would basically measure the length of the indentation and return enough spaces/tabs to replace it.

**Comment by davidderaedt** [comment]
Absolutely, I will remove the extension from Brackets official list until it's fixed

**Comment by davidderaedt** [comment]
The latest update should fix this issue and work as intended, that is only perform conversion to indentations, leaving the document string untouched.

**Comment by DennisKehrig** [comment]
Sweet! On consistently indented files, it does indeed work now!
